### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by vitormicillo** [kanflo/ADS-B-funhouse#11]
Hi, I'm trying to test your code with my dump1090-fa on a rockPI with python 3.11, but I'm getting some errors when running pip install because of some dependencies.
I have attached a console report for you, I really appreciate it if you have any spare time to have a look in this strange error.

![image](https://github.com/kanflo/ADS-B-funhouse/assets/1921806/47c7f936-061a-429f-9e4b-e1053c8a99ef)

**Comment by kanflo** [comment]
Oh, a minor omission on my part. Please pull and it should work.
