### ISSUE TITLE
Issue with mqttOnConnect()

### ISSUE THREAD

**Issue by DarS007** [kanflo/ADS-B-funhouse#2]
Thanks for your code!
I'm trying to run it on my RPi (with RTL-SDR dongle), but the code shows error with mqttOnConnect() subroutine. Any chance that you can help?
`2018-06-29 - __main__ - ERROR - MQTT thread got exception: mqttOnConnect() takes exactly 3 arguments (4 given)`
`2018-06-29 - __main__ - INFO - ADSB connected`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner`
`    self.run()`
`  File "/usr/lib/python2.7/threading.py", line 763, in run`
`    self.__target(*self.__args, **self.__kwargs)`
`  File "./adsbclient.py", line 227, in mqttThread`
`    print traceback.format_exc()`
`NameError: global name 'traceback' is not defined`
`2018-06-29 - __main__ - CRITICAL - Exiting`

I did some basic troubleshooting and it looks that for some reason my adsbclient.py has problem connecting to MQTT:
**1) - simple run without MQTT works flawlessly**
`./adsbclient.py`
`2018-06-29 17:44:15,884 - __main__ - INFO - ADSB connected`
**2) - similar run but with MQTT defined fails**
`./adsbclient.py -m mqttsrv.homenet`
`2018-06-29 - __main__ - ERROR - MQTT thread got exception: mqttOnConnect() takes exactly 3 arguments (4 given)`

Of course the MQTT server is up and accessible,

Regards,
-DarS

**Comment by kanflo** [comment]
Glad someone is using this old project of mine :D Thanks for the report, it seems the function ```mqttOnConnect```was missing one parameter. Strangely enough, my Python runtime never complained.

**Comment by DarS007** [comment]
Re. using this old code - yeah, this is the beauty of open source I guess :-)   I was searching for the _ADS-B to MQTT bridge_, and your code is really great!! I am amazed how efficient Python can be in hands of talented people.
Regarding the bug with `mqttOnConnect()` - in the meantime I added some dummy 4th argument and ... voila! Works now. Thanks!
