### ISSUE TITLE
Usage confusion - new code

### ISSUE THREAD

**Issue by DarS007** [kanflo/ADS-B-funhouse#6]
Thanks for the code updates! I'm trying to restore my ADS-B to MQTT bridge, so I installed the latest from GitHub. 
On a single host I run ADS-B receiver, _Plane database server_ and _flighttracker.py_
```
> ./planedb-serv.py` flightdata.sql 31541
> ./flighttracker.py -H localhost -m mqtt.housenet -pdb localhost -l XX.XX -L YY.YY --prox Flight
```
_flighttracker.py_ successfully connects to ADS-B server and announces about the planes
```
ERROR    flighttracker.py  133 icao24 3C7E11 not found in the database
INFO     flighttracker.py  520 33FDFC disappeared
INFO     flighttracker.py  520 1420D9 disappeared
INFO     flighttracker.py  506 Found nothing to track
```
but the script is not able to track any plane (thus not generating any MQTT messages). 

**Question**  Can I use your new _flighttracker.py_ script to generate MQTT messages having empty local Plane database? Knowing of course that MQTT messages will miss all airplane-related data.  
Or filling the database is the necessary prerequisite for the script to work as MQTT bridge?
Regards!
-DarS007

**Comment by kanflo** [comment]
Only planes found in the database will be announced. These are referred to as "presentable" in the code but if you make a small change here:

https://github.com/kanflo/ADS-B-funhouse/blob/485a9c372e41b8f8c295169d870f14d62df3aa42/flighttracker.py#L499

then everything will be published.
