### ISSUE TITLE
Building a Plane DB

### ISSUE THREAD

**Issue by luke-iqt** [kanflo/ADS-B-funhouse#7]
Do you have any tips on building the Plane DB? It looks like this library maybe able to pull most of the information from the OpenSky database: https://traffic-viz.github.io/aircraft.html 

Do you think shifting over to use the OpenSky DB could provide most of the information needed?
https://opensky-network.org/datasets/metadata/

**Comment by kanflo** [comment]
I tried installing the lib but it pulled a ton of dependencies related to cartography. I think a small script to download the OpenSky database and syncing to PlaneDB would be a better option. Maybe Santa brings a PR for Christmas ;)

**Comment by luke-iqt** [comment]
Good call - I have been trying things out using the OpenSky Data and it seems to be pretty complete for the planes I am seeing in the US. I have been hacking something together that is quick and ugly - I am trying to use this data to point a camera and take pictures as the planes go by. If I get everything work, I can see if I can come up with something more elegant and put in a PR.
